// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wsyuysthfrjnxuasceqd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndzeXV5c3RoZnJqbnh1YXNjZXFkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzM3NDg3NjgsImV4cCI6MjA0OTMyNDc2OH0.xtZpjumfH8IQmNvpYx2ZEPOD1hCYdzfq-yI9M1d-A8Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);